@extends('layout.main')
@section('container')
<main id="main">

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Loco London Gold</h2>
          <ol>
            <li><a href="/">Home</a></li>
            <li>Edukasi</li>
            <li>Loco London Gold</li>
          </ol>
        </div>

      </div>
    </section><!-- End Breadcrumbs Section -->

    <section class="inner-page">
      <div class="container">
        <div itemprop="articleBody">
          <h2 class="contentheading" style="padding: 0px; margin: 0px; font-family: Tahoma,Arial,Helvetica,sans-serif; font-size: 22px; color: #333333; text-align: justify;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Emas merupakan salah satu jenis komoditi yang paling banyak diminati untuk tujuan investasi. Di samping itu, emas juga digunakan sebagai standar keuangan atau ekonomi, cadangan devisa dan alat pembayaran yang paling utama di beberapa negara. Para investor umumnya membeli emas untuk&nbsp;<em style="padding: 0px; margin: 0px;">hedge</em>&nbsp;atau&nbsp;<em style="padding: 0px; margin: 0px;">safe haven</em>&nbsp;terhadap beberapa krisis termasuk ekonomi, politik, sosial atau krisis yang berbasis mata uang.</span></h2>
      <div class="article-content" style="padding: 0px; margin: 0px; font-size: 11px; font-family: Tahoma,Arial,sans-serif; line-height: 16.5px; text-align: justify;">
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Permintaan emas fisik mengalami peningkatan cukup signifikan dari tahun ke tahun. Padahal cadangan emas dunia sangatlah terbatas. Oleh karena itu, dibeberapa negara maju telah menyediakan investasi alternatif berupa produk derivatif emas dengan menarik sejumlah&nbsp;<em style="padding: 0px; margin: 0px;">margin</em>&nbsp;sebagai jaminan transaksinya (<em style="padding: 0px; margin: 0px;">margin trading</em>). Mengapa diperlukan&nbsp;<em style="padding: 0px; margin: 0px;">margin</em>?. Ini karena adanya faktor harga, dimana harga emas juga dapat berfluktuasi sebagaimana komoditas lainnya.</span></p>
      <p>&nbsp;</p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">&nbsp;<strong style="padding: 0px; margin: 0px;">A.&nbsp;&nbsp; </strong><strong style="padding: 0px; margin: 0px;">Sejarah Perdagangan Emas</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Di dalam pasar komoditas istilah "Loco" berarti "di". Berasal dari bahasa latin Locus yang berarti tempat. Loco London merepresentasikan basis perdagangan dan penyelesaian emas dan perak internasional di London.&nbsp;Pelaksanaan pasar ini di bawah naungan London Bullion Market Association (LBMA), namun bukan bursa.&nbsp;</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Pasar emas fisik (<em style="padding: 0px; margin: 0px;">spot gold</em>) terbesar dunia adalah London dan Zurich, akan tetapi London yang paling menonjol. London tumbuh mendominasi pasar emas pada saat emas menjadi mata uang utama. Penemuan signifikan di Ural (Rusia) telah meningkatkan produksi emas global di abad 18.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Pertengahan abad 19 menjadi momen bagi Inggris untuk mendominasi perdagangan dan keuangan dunia, sebagai sumber modal untuk pertambangan emas, dan menjadi standar emas mata uang lokal, British Pound. Sehingga London menjadi pusat perdagangan dan penyelesaian emas dunia.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">Perdagangan Over-the-Counter (OTC)</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Pasar emas London merupakan pasar Over-The-Counter yang berarti perdagangan dilakukan secara langsung antara dua pihak yang terlibat, dan tidak melalui pihak ketiga yang mengatur perdagangan, seperti bursa.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Pasar OTC berlangsung selama 24 jam sehari dan tidak mempunyai struktur formal dan tidak ada tempat pertemuan sentral. Sebagian besar perdagangan dilakukan melalui telpon atau sistem dealing elektronik.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Di pasar finansial global saat ini, perdagangan emas di London hampir terselenggara sepanjang waktu diseluruh dunia. Harga&nbsp;<em style="padding: 0px; margin: 0px;">bid</em>&nbsp;dan&nbsp;<em style="padding: 0px; margin: 0px;">ask</em>&nbsp;dikuotasikan secara kontinu di dalam sistem informasi pasar finansial yang dapat diakses seperti Reuters. Selain di London, pusat perdagangan utama lainnya untuk emas London termasuk New York, Zurich, Tokyo, Sydney dan Hong Kong, dimana Hong Kong menjadi pusat perdagangan di Asia.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">Mengapa berinvestasi di emas (<em style="padding: 0px; margin: 0px;">Spot&nbsp;</em>OTC)</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">1. Harga biasanya dikuotasikan dan diperdagangkan terhadap dolar AS;</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">2. Loco London Market dapat melayani beberapa tujuan transaksi seperti&nbsp;<em style="padding: 0px; margin: 0px;">hedging</em>, investasi dan spekulasi;</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">3. Di pasar OTC, investor dapat mempertahankan posisi mereka selama waktu yang mereka inginkan tanpa ada jatuh tempo;</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">4. Menerima bunga saat menjual emas atau perak Loco-London pada suku bunga terakhir;</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">5. Transaksi&nbsp;<em style="padding: 0px; margin: 0px;">leverage</em>&nbsp;pada margin;</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">6. Diversifikasi portfolio investasi.</span></p>
      <p>&nbsp;</p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">&nbsp;B.&nbsp;&nbsp; </strong><strong style="padding: 0px; margin: 0px;">Pasar Emas Dunia</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">1. Loco London Gold Market</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Di London, emas dan perak diperdagangkan oleh anggota-anggota London Bullion Market Association (LBMA), diawasi oleh Bank of England. Sebagian besar anggota-anggotanya adalah bank-bank internasional atau&nbsp;<em style="padding: 0px; margin: 0px;">bullion dealer</em>&nbsp;dan sejumlah&nbsp;<em style="padding: 0px; margin: 0px;">refiner</em>&nbsp;raksasa.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Perdagangan emas di pasar London memiliki sejarah panjang selama 3 abad, dan&nbsp;<em style="padding: 0px; margin: 0px;">Gold Fixing</em>&nbsp;(penetapan harga emas) hanya dibentuk setelah Perang Dunia I pada tahun 1919. Sistem <em style="padding: 0px; margin: 0px;">Fixing</em>&nbsp;ini berasal dari pasar perak London dan suatu konsep bagi investor seluruh dunia untuk melakukan beli dan jual emas pada&nbsp;<em style="padding: 0px; margin: 0px;">single</em>&nbsp;<em style="padding: 0px; margin: 0px;">quoted price</em>.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><em style="padding: 0px; margin: 0px;">Fixing</em>&nbsp;secara harian dilakukan 2 kali yakni pada pukul 10:30 am (16:30 wib) dan 15:00 pm (21:00 wib) di London dengan melibatkan 5 Anggota Fixing sebagai berikut:</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">- Scotia-Mocatta, suksesor Mocatta &amp; Goldsmid dan menjadi bagian Bank of Scotia</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">- Barclays Capital, menggantikan N. M. Rothschild &amp; Sons Limited</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">- Deutsche Bank, owner&nbsp;Sharps Pixley</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">- HSBC, owner Samuel Montagu &amp; Co.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">- Société Générale, menggantikan Johnson Matthey dan CSFB (Credit Suisse First Boston)</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">2. Pasar Emas Amerika</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Di tahun 1975, America NewYork Commodity Exchange COMEX memulai perdagangan&nbsp;<em style="padding: 0px; margin: 0px;">forward</em>&nbsp;emas, menjadi sentral perdagangan&nbsp;<em style="padding: 0px; margin: 0px;">forward</em>&nbsp;emas dunia. Kini, pasar berjangka emas New York menggantikan status pasar di London dalam mengatur harga emas dunia. Alasan mengapa hal ini terjadi?&nbsp; Karena pasar New York memiliki keuntungan di dalam metode transaksi, <em style="padding: 0px; margin: 0px;">aggregate supply</em>,&nbsp;<em style="padding: 0px; margin: 0px;">marked price</em>&nbsp;dan waktu transaksi.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">3. Pasar Emas Hong Kong</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Pasar emas di Hong Kong dikenal juga sebagai pasar emas Loco (Local) London. Kini market mempunyai sekitar 70 partisipan yang bertransaksi aktif, sebagian besar bank, perusahaan investasi dan pedagang emas lokal untuk&nbsp;<em style="padding: 0px; margin: 0px;">hedge</em>&nbsp;terhadap posisi-posisi mereka di pasar berjangka. Pasar emas Loco London ini dikuotasikan dalam&nbsp;<em style="padding: 0px; margin: 0px;">US dollar per troy ounce</em>&nbsp;emas murni 99,99% dan dengan penyerahan di London.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Chinese Gold and Silver Exchange Society mengoperasikan salah satu pasar emas terbesar di dunia. Emas yang diperdagangkan melalui lembaga ini memiliki kemurnian 99%, satuan berat dengan tael dan dikuotasikan dalam dolar Hong Kong. Harganya hampir mengikuti pasar emas besar lainnya di London, Zurich dan New York.&nbsp;<em style="padding: 0px; margin: 0px;">Turnover</em>&nbsp;di dalam bursa sebanyak 4,3 juta tael di 2001.</span></p>
      <p>&nbsp;</p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">&nbsp;<strong style="padding: 0px; margin: 0px;">C.&nbsp;&nbsp; </strong><strong style="padding: 0px; margin: 0px;">Analisis Harga Emas</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Pada kenyataan sehari-hari, harga emas tidak hanya tergantung kepada situasi permintaan dan penawaran, atau&nbsp;<em style="padding: 0px; margin: 0px;">supply</em>&nbsp;and&nbsp;<em style="padding: 0px; margin: 0px;">demand</em>. Harga emas juga dipengaruhi oleh situasi perekonomian secara keseluruhan.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Berikut ini beberapa situasi ekonomi yang sering mempengaruhi harga emas:</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">1. Perubahan kurs</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Melemahnya kurs dolar AS biasanya mendorong kenaikan harga emas dunia. Hal ini disebabkan karena para investor memilih untuk menjual mata uang dollar milik mereka dan kemudian membeli emas yang dinilai mampu melindungi nilai asset yang mereka miliki. Sebagai contoh, pada medio Oktober 2009, nilai tukar mata uang dolar terhadap mata uang lain terus menurun, sementara harga emas terus naik sampai ke level $1.070 per&nbsp;<em style="padding: 0px; margin: 0px;">troy ounce</em>&nbsp;yang merupakan harga emas tertinggi sepanjang sejarah.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">2. Situasi politik dunia</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Kenaikan harga emas pada akhir tahun 2002 dan awal tahun 2003 terjadi sebagai dampak dari akan dilakukannya serangan ke Irak oleh sekutu yang dikomando AS. Pelaku pasar beralih investasi dari pasar uang dan pasar saham ke investasi emas sehingga permintaan emas melonjak tajam.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">3. Permintaan dan penawaran<br></strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Salah satu contoh hal yang dapat mempengaruhi permintaan dan penawaran (<em style="padding: 0px; margin: 0px;">supply and demand</em>) dari emas adalah seperti kejadian pada pertengahan tahun 1980. Pada saat itu, penjualan <em style="padding: 0px; margin: 0px;">forward</em>&nbsp;oleh perusahaan pertambangan selalu dipersalahkan atas terjadinya kenaikan pada harga emas. Dalam kerangka bisnis, sebenarnya perilaku perusahaan pertambangan tersebut masuk akal. Dengan melakukan penjualan&nbsp;<em style="padding: 0px; margin: 0px;">forward</em>&nbsp;ketika harga emas menguat, mereka dapat mengamankan harga&nbsp;<em style="padding: 0px; margin: 0px;">output</em>&nbsp;tambang pada harga yang cukup menarik.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Contoh lainnya, kasus pada pertengahan tahun 1998 di mana harga emas terus merosot. Saat itu, bank-bank sentral di Eropa menyatakan akan mengurangi cadangan emasnya sehubungan rencana pemberlakuan mata uang euro. Harga emas langsung anjlok di sekitar 290 dolar per&nbsp;<em style="padding: 0px; margin: 0px;">troy ounce</em>.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">4. Situasi ekonomi global</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Sekitar 80 persen dari total suplai emas digunakan industri perhiasan. Konsumsi perhiasan merupakan pengaruh yang besar pada sisi permintaan.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Ketika kondisi ekonomi meningkat, kebutuhan akan perhiasan cenderung naik. Namun, dari data statistik terlihat kebutuhan akan perhiasan lebih sensitif terhadap naik turunnya harga emas dibandingkan meningkatnya kondisi ekonomi.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Jatuhnya tingkat kebutuhan perhiasan pada masa resesi di tahun 1982-1983 terutama akibat naiknya harga emas secara simultan. Jatuhnya tingkat kebutuhan perhiasan di masa resesi awal 90-an lebih selaras dengan hal di atas, pada saat itu harga emas menjadi turun.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Situasi ekonomi yang tidak menentu dapat mengakibatkan inflasi tinggi. Emas biasa digunakan sebagai alat lindung nilai terhadap inflasi. Manfaat ini sudah dirasakan investor sejak lama. Dengan emas, investor mendapat perlindungan sempurna terhadap merosotnya daya beli. Ketika tahun 1978-1980 harga emas sedang&nbsp;<em style="padding: 0px; margin: 0px;">booming</em>; sementara inflasi di AS naik dari 4 persen menjadi 14 persen, harga emas naik 3 (tiga) kali lipat.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">5. Suku bunga</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Ketika tingkat suku bunga naik, ada usaha yang besar untuk tetap menyimpan uang pada deposito ketimbang emas yang tidak menghasilkan bunga (<em style="padding: 0px; margin: 0px;">non interest-bearing</em>). Ini akan menimbulkan tekanan pada harga emas. Sebaliknya, ketika suku bunga turun, harga emas akan cenderung naik.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Secara teori, jika suku bunga jangka pendek naik, harga emas turun. Di Indonesia teori ini tidak selalu berjalan.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Pada tahun 1998, karena nilai tukar rupiah merosot tajam terhadap mata uang dolar AS, pemerintah menaikkan tingkat suku bunga secara signifikan. Harapannya, menahan laju kenaikan nilai tukar dolar AS. Akibatnya, walaupun tingkat suku bunga naik, harga emas juga naik.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">&nbsp;</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;"><strong style="padding: 0px; margin: 0px;">&nbsp;D.&nbsp;&nbsp; </strong><strong style="padding: 0px; margin: 0px;">Kontrak Derivatif Emas Loco London (SPA)</strong></span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-family: 'Open Sans', sans-serif; font-size: 10pt;">Kini kontrak derivatif emas Loco London sebagai objek transaksi derivatif melalui Sistem Perdagangan Alternatif (SPA), berdasarkan Peraturan Kepala Badan Pengawas Perdagangan Berjangka Komoditi (Bappebti) bernomor 72/BAPPEBTI/Per/9/2009. Selain emas, dua produk lainnya adalah kontrak derivatif antar mata uang asing (<em style="padding: 0px; margin: 0px;">foreign cross currencies</em>) dan indeks.</span></p>
      <p style="padding: 0px; margin-top: 12px; margin-bottom: 12px;"><span style="font-size: 8pt;"><em><span style="font-family: 'Open Sans',sans-serif;">*) Diolah dari beberapa sumber</span></em></span></p>
      </div>	</div>
      </div>
    </section>

  </main><!-- End #main -->
@endsection